### ISSUE TITLE
Figure out how to release packages to not break builds

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#101]
Right now I had several broken builds just after releasing packages because when Travis started tests for packages like `ckeditor5-autoformat` their deps were still unreleased.

So either we mark release commits as `[skip ci]` or we need to release packages in a different order (i.e. topological order). I'd like to have Travis running tests for the new releases (which ensures we haven't broken something), so the topological sorting seems to be the only option.

**Comment by pomek** [comment]
After merging https://github.com/ckeditor/ckeditor5-dev/pull/281 this issue will not be valid anymore.

**Comment by pomek** [comment]
After splitting the release process into two parts: tagging and publishing, the described problem will not occur anymore because even if NPM or/and GitHub fail, we can run the publishing script again. 

It will publish only packages which versions on the local machine are different than on the mentioned services. See https://github.com/ckeditor/ckeditor5-dev/pull/431.
