### ISSUE TITLE
Merge commits are ignored when releasing sub packages

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#172]
See https://github.com/ckeditor/ckeditor5-dev/pull/154#issuecomment-297476399.

**Comment by pomek** [comment]
You're right, we have a bug – for merge commits, util `getChangedFilesForCommit()` returns an empty string. This bug can be fixed by changing the git command:

```js
`git log -m -1 --name-only --pretty="format:" ${ commitId }`
```

instead of 

```js
`git show --pretty="" --name-only ${ commitId }`
```

Let me explain why we have a problem with the merge commit.

Commit fefc1de92d89761e30cbc1b23d09ece0ce6403f8 is not valid from `ckeditor5-dev-env` POV because the commit touched files from other packages

![image](https://cloud.githubusercontent.com/assets/2270764/25471054/835d5a22-2b25-11e7-9b2f-3150ff47cb65.png)

and from the root directory of the whole repository:

![image](https://cloud.githubusercontent.com/assets/2270764/25471080/a99cf756-2b25-11e7-803e-9ebcb36b7708.png)

When I was creating the changelog tool for sub packages, I wanted to accept non-packages files – https://github.com/ckeditor/ckeditor5-dev/commit/dd5a227dcc91532b6e1633a9be0a634cce6dec3a#diff-4e3a65e4a297b85fa9222ca681c89f45L38 – but I abandoned it. Maybe an idea wasn't stupid and we should restore it…

**Comment by Reinmar** [comment]
I wouldn't complicate this – if this commit touched files from other packages, it should propose bumping up versions in those packages too. This is a situation we need to resolve manually for now.

In the future, we can simplify the way to resolve it – e.g. we could print which files changed in which package, we could have a configurable set of ignored files like Lerna has, etc. But first of all, we need to have this bug fixed.
