### ISSUE TITLE
gulp docs:api does not work after upgrading JSDoc to version 3.5.1

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev#240]
JSDoc which is required by [`gulp-jsdoc3`](https://github.com/mlucool/gulp-jsdoc3/blob/master/package.json#L51) has been released with new version – [`3.5.1`](https://github.com/jsdoc3/jsdoc/releases/tag/3.5.1).

Unfortunately, one of our plugin after this upgrading does not work…

```
[07:18:30] /home/travis/build/ckeditor/ckeditor5/node_modules/@ckeditor/jsdoc-plugins/lib/longname-fixer/fixers/fix-links.js:17
		if ( !doclet.memberof.includes( className ) ) {
		                     ^
TypeError: Cannot read property 'includes' of undefined
```

See more on Travis logs: https://travis-ci.org/ckeditor/ckeditor5/builds/251965531#L1986

**Comment by ma2ciek** [comment]
As I said internally, the Error occurred because of the change in JSDoc hooks.
Now, `newDoclet` doesn't run doclet by doclet within a file, but more "randomly" between many files. As a result old approach with fixing events' `memberof` property doesn't work.

**Comment by Reinmar** [comment]
Switched to our fork of gulp-jsdoc3 in https://github.com/ckeditor/ckeditor5-dev/commit/aca81242d15cffae45bf417eca66ea9bb2a8ad72.

**Comment by ma2ciek** [comment]
JSDoc changed the parser in version 3.5. (from https://github.com/hegemonic/catharsis to https://github.com/babel/babylon). So the tree walker that walks through the AST has changed too. I'll report it, but I don't think it might be an easy-to-solve thing.

**Comment by ma2ciek** [comment]
I forgot to report it then 😞 We stopped upgrading JSDoc at "jsdoc": "3.4.3" because of the above change. We have got many custom plugins that use the Doclet API which content and the order is the essential thing for our docs building process. I can check out the newest version to see if the upgrade is feasible now (maybe the above error was fixed in later releases). But as the current version works for us and the https://github.com/jsdoc3/jsdoc project hasn't any upgrade since https://github.com/jsdoc3/jsdoc/releases/tag/3.5.5 (September 2017) I don't think this research is valuable.
