### ISSUE TITLE
JSDoc validator - validate modules, classes etc. existence

### ISSUE THREAD

**Issue by m-turek** [ckeditor/ckeditor5-dev#248]
Sometimes a module is referenced by another item but the module itself doesn't exist.

Example: https://github.com/ckeditor/ckeditor5-ui/blob/master/src/dropdown/list/listdropdownview.jsdoc#L12

**Comment by wwalc** [comment]
This is a really nice to have feature imho as I'm constantly visiting places like this while browsing the documentation: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_ui_panel_balloon_contextualballoon-ContextualBalloon.html

![screen shot 2017-08-30 at 17 48 27](https://user-images.githubusercontent.com/545175/29881644-7638eaa8-8dab-11e7-973f-a872e7cf694c.png)

**Comment by ma2ciek** [comment]
There's already a link validator (https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/jsdoc-plugins/lib/validator/doclet-validator.js#L152). The problem here was, that the `@link` phrase was missing inside the curly brackets. (https://github.com/ckeditor/ckeditor5-ui/blob/master/src/panel/balloon/contextualballoon.js#L18). If you'll find more, please let me know. I'm not sure whether the above case should be handled, but it shouldn't be hard to implement.

**Comment by wwalc** [comment]
> The problem here was, that the @link phrase was missing inside the curly brackets. 

Ops true, did not check the source. The lack of `@link` there makes that particular sample "invalid". I don't think we need to detect cases like this then automatically.

**Comment by ma2ciek** [comment]
I'm closing this as no such error occurred in the meantime.
Please, reopen, when you hit it again.
