### ISSUE TITLE
When reporter should be set to dots by default?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#305]
Currently, when running `npm t` in ckeditor5 the reporter will not be automatically set to `dots` because the same task is used for normal development in which, I assume (?), we rather prefer the normal reporter. However, when running many tests, the normal reporter just makes the output unreadable.

So, one idea that came to my mind that reporter should be automatically set to `dots` when not passing `--files` or passing `--files=*` (the same thing).

Also, with https://github.com/ckeditor/ckeditor5-dev/pull/304 we can perhaps predict how many files will be tested and set the reporter automatically to `dots` when the number exceeds e.g. 10. 

Or maybe we can set the reporter to dots by default and allow setting it to the current one using `--reporter` (in other words – revert the setting)?

WDYT?

**Comment by pomek** [comment]
> Or maybe we can set the reporter to dots by default and allow setting it to the current one using --reporter (in other words – revert the setting)?

👍

**Comment by scofalik** [comment]
I was about to write that I'd like `dots` only for `--files=*` because it makes sense development wise.

When you are testing a new feature or changes in existing feature, you probably would like to have the whole listing to know which tests are failing. The assumption is that several tests will fail, etc.

OTOH, when you run tests for whole repo you just want to make sure that you didn't break anything. You assume that everything will be green.

But I am not sure. Maybe this is just the way I am used to and I am just defending it because of that.

**Comment by pomek** [comment]
Dots reporter prints which test fails:

![image](https://user-images.githubusercontent.com/2270764/32731040-0ed0e49c-c889-11e7-9a46-88ba47eb0dc5.png)

**Comment by scofalik** [comment]
I know but it is not nice. For example, assumes and expects are better looking in what we have now default. Also the test title is put into one sentence instead of broken down by `describe`s.

Check out the structure and how results are compared in the second test:

![image](https://user-images.githubusercontent.com/1502228/32731222-897b664a-c889-11e7-9560-f8760362fd2d.png)

The truth is if there would be failing tests and dot reporter is the default, I'd re-run tests with the current reported just to have it nice looking.

**Comment by jodator** [comment]
For dev I'd like to have clear info which test failed and why. So for me it's not dots (`mocha` AFAIR).

The dot's looks like good for Travis though.

**Comment by oskarwrobel** [comment]
It's OK for me to have `mocha` as default reporter and optional `dots` by `--reporter dots`. I agree that `dots` reporter has more sense when many tests run but I'm not for guessing when we should use `dost` or `mocha`. Mocha - default, dots - optional.
