### ISSUE TITLE
typedef in "jsdoc-plugins/validator"

### ISSUE THREAD

**Issue by ozum** [ckeditor/ckeditor5-dev#456]
Hi,

I'm using `@ckeditor/jsdoc-plugins` in my project and it's very helpful, thanks for the module.

I have a problem defining and using `@typedef`. I list all types used project wide in a dedicated file, say `src/typedef.js`.

I tried to use global typedef names and module bound names, but could not pass validator of `@ckeditor/jsdoc-plugins` and get errors. I appreciate any help.

Please see examples below:

## Global Name

**src/typedef.js**
```js
/**
 * @typedef {String}        UUID
 */
```

**src/index.js**
```js
{
    /**
     * Name of the item.
     * @type {UUID}
     */
    name: this.string(""),
}
```

**Error**: `Invalid @property type: UUID.`

## Module Prefix Name

**src/typedef.js**
```js
/**
 * @memberof                module:Types
 * @typedef {String}        UUID
 */
```

**src/index.js**
```js
{
    /**
     * Name of the item.
     * @type {module:Types.UUID}
     */
    name: this.string(""),
}
```

**Error**: `Link misses the '@link' part: {module:Types.UUID}`

**Comment by Reinmar** [comment]
Hi! Thanks for the report. It seems that our link validator catches more than it should. I wonder why it even scans this fragment of the doclet.

cc @ma2ciek

**Comment by ma2ciek** [comment]
> Hi! Thanks for the report. It seems that our link validator catches more than it should

Yep, it seems it does. I'll investigate it.

**Comment by ma2ciek** [comment]
Hi, @ozum!

Are you sure that you don't miss the `@` before the `type` in the `@type` tag? Because the simple algorithm that searches for missing `@link` tags, first match the `/(@[a-z]+ )?\{[^}]+\}/g` regex and then checks if the first part (the one in the parenthesis) actually doesn't start with `{module:`.

If the first part starts with `{module:`, then it means that it isn't preceded with any tag that starts with `@` and it means that it possibly a broken link. Your snippet contains the `@type {module:Types.UUID}` so it should not be matched. I've tried to create a unit test but I've failed to reproduce it.

Anyway, I'm glad that you find this package useful :)

**Comment by ozum** [comment]
Hi @ma2ciek, this package is lifesaver, I couldn't believe number of typos in my jsdoc.

I rechecked. Trying to simplify, I gave wrong example. My actual source code is as below. Could you check this please?

```js
/**
 * Class which represents `{@link module:store.entities.Item Item}` categories.
 * @memberof module:store.entities
 */
class Category extends Model {}
```

```js
class ItemList extends Vue {
  /**
   * All categories with items.
   * @type {module:store.entities.Category[]}
   * @private
   */
  get categories() {}

  onAdd(item) {
    /**
     * `add` event fires when add button is clicked.
     * @event ItemList#add
     * @type {String} item  - Item id
     */
    this.$emit("add", item.id);
  }
```

1. I try to use Category class as a type
2. I had to prefix event name with `ListItem#`. Otherwise jsdoc did not detect that it is a part of the class it is written in.

I got following validation errors:
* Link misses the '@link' part: {module:store.entities.Category[]}
* Memberof property should start with 'module:'. Got 'ItemList' instead.



Thanks.

**Comment by ma2ciek** [comment]
> Link misses the '@link' part: {module:store.entities.Category[]}

I'll try to reproduce it, the above usage should be fine

> Memberof property should start with 'module:'. Got 'ItemList' instead.

That's because JSDoc needs to know which symbols are available in which module. And we enforce that to be able to link these symbols later and validate them. So in your example, you need to define the `@memberof` of that class or write the module declaration at the top of the file:
```
/**
 * @module someModule
 */
```

> I had to prefix event name with ListItem#. Otherwise jsdoc did not detect that it is a part of the class it is written in.

According to the http://usejsdoc.org/tags-event.html, we follow a little bit different approach to event names to avoid event and class member collisions. See https://github.com/ckeditor/ckeditor5-dev/tree/master/packages/jsdoc-plugins and e.g. https://github.com/ckeditor/ckeditor5-engine/blob/master/src/model/selection.js to see how we use `@event` and `@fires` tags. We use the https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/jsdoc-plugins/lib/longname-fixer/longname-fixer.js that allows the short notation.

In your example the event should be declared later in the class and you should use `@fire` tag before the emit.

PS I see that the readme misses few things, I'll try to fill it with them, feel free to ask.

**Comment by ozum** [comment]
@ma2ciek, thank you for the informative answer.

I added `@module someModule` at the beginning of the file and started to use other @ckeditor plugins.  All problems are solved. You don't need to try to reproduce.

Lessons I learned (Please correct if I'm wrong)
1. Use `validator` plugin with other `@ckeditor/jsdoc-plugins` together i.e. `longname-fixer`
2. Every file needs a `@module` tag at the beginning

It may be better to add a rule to validator plugin to check whether `@module` tag exists in files. This will prevent most of the other errors and points root cause.

Not related to plugins but I have question when I see it on https://github.com/ckeditor/ckeditor5-engine/blob/master/src/model/selection.js and I will appreciate if you could help.

When I have no js code after a jsdoc comment, it is not generated in documents. How did you solve that?

```js
class ItemList extends Vue {
   // Some code

  /**
   * `add` event fires when add button is clicked.
   * @event add
   * @type {module:Types.UUID} item  - Item id
   */
}
```

`add` event is not documented so I have to put some code to document it.

```js
class ItemList extends Vue {
   // Some code

  /**
   * `add` event fires when add button is clicked.
   * @event add
   * @type {module:Types.UUID} item  - Item id
   */
   stub() {} // Does nothing :(
}
```

**Comment by ma2ciek** [comment]
> 1. Use validator plugin with other @ckeditor/jsdoc-plugins together i.e. longname-fixer
> 1. Every file needs a @module tag at the beginning

> It may be better to add a rule to validator plugin to check whether @module tag exists in files. This will prevent most of the other errors and points root cause.

Yes, you're right. I'd change just the error message as detecting missing modules won't be easy.

> When I have no js code after a jsdoc comment, it is not generated in documents. How did you solve that?

This happens probably because of the `@type` tag. We use `@param` tags to specify types of the event parameters.

**Comment by ozum** [comment]
Thanks.
