### ISSUE TITLE
The new package has not been pushed to GH during the release

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#491]
That's the state after runnign the release script:

![image](https://user-images.githubusercontent.com/156149/53565339-7e622480-3b59-11e9-8747-c57337d300fa.png)

Also: 

![image](https://user-images.githubusercontent.com/156149/53565412-b701fe00-3b59-11e9-8b03-5bcc1a106af4.png)

**Comment by pomek** [comment]
If there is no log from `npm run release:publish`, I wish good luck to myself during debugging this.

**Comment by pomek** [comment]
By the way, this task can be called a few times in the row (it's by its design) and if anything has not been published, you can try to publish it again.

If the mentioned issue could repeat then we would know that the tool has the bug. Now we have nothing because there is no log from the tool and no more attempts to release the changes.

**Comment by pomek** [comment]
The title of the issue suggestes that the `git push` command failed or didn't be executed which isn't true because on the attached screen I can see the commit ID:

![image](https://user-images.githubusercontent.com/2270764/53811294-51e34980-3f59-11e9-9959-1c2ef2d5cd4e.png)

(which is equal to the release commit).

So the question is – what did fail? Git push or the release on GH wasn't created?

**Comment by Reinmar** [comment]
The title says that the push didn't work. It does not say push of what.

And the git log shows this:

![image](https://user-images.githubusercontent.com/156149/53811721-49d7d980-3f5a-11e9-94fc-1aa2d00b5a53.png)

It shows that master has not been pushed correctly. The other screenshot in the issue shows that there's no release notes for this release.

There were no suspiscious logs on the console. I suppose there's some incorrect `if()` in the code. You were already fixing a bug in it once – do you remember that issue?

**Comment by pomek** [comment]
> You were already fixing a bug in it once – do you remember that issue?

Unfortunately, I don't :(

I will try to reset the state of this package before we started releasing it. Also, I will mock responses returned by `npm` and GH API that allows me calling dry run mode on this package.

**Comment by pomek** [comment]
Ok, I know what went wrong. Github returns:

> Checking "@ckeditor/ckeditor5-mention"...
>```
>{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/releases/#get-the-latest-release"}
>```

For package that has 0 releases.

**Comment by pomek** [comment]
It will also fail for publishing on NPM:

```
Checking "@ckeditor/ckeditor5-mention"...
⚠️   Execute: "npm show @ckeditor/ckeditor5-mention version" in "/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-mention".
npm ERR! code E404
npm ERR! 404 '@ckeditor/ckeditor5-mention' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404
npm ERR! 404  '@ckeditor/ckeditor5-mention@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pomek/.npm/_logs/2019-03-14T10_43_08_710Z-debug.log
```

**Comment by pomek** [comment]
It's funny because we had a check for the reported case:

https://github.com/ckeditor/ckeditor5-dev/blob/a365f08548fba4af88f9d233826d603c93358529/packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js#L318-L325

It means that Github has changed something in its API and it impacted our code.

**Comment by pomek** [comment]
For the future references, if something went wrong, check the entire log from executed task. In this case, there was an answer:

![image](https://user-images.githubusercontent.com/2270764/54355237-d0767000-4658-11e9-8201-e8df17feaa7e.png)

Grey logs are always printed. Even if the script will continue. Even in _production_ mode.
