### ISSUE TITLE
CKEditor Webpack plugin does not work anymore after CKEditor switched to scoped dependencies

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-dev#53]
I believe it's because of this line: https://github.com/ckeditor/ckeditor5-dev/blob/c7fc65cd9f795255dee0bccc83a0b8cf3915af86/packages/ckeditor5-dev-utils/lib/compiler/resolveimportpathincontext.js#L15

**Comment by Reinmar** [comment]
Yep, it's not supposed to work now, because it's not needed ATM. We may bring the redirect option back at some point, but it isn't necessary now. You have Webpack's resolution paths which you can use, and for development purposes (for which the plugin [was useful](https://github.com/ckeditor/ckeditor5/issues/362#issuecomment-268994408)) we rather favor symlinks done by Lerna.

**Comment by Reinmar** [comment]
I confirmed this issue, more as a reminder that we need to do something with this piece of functionality than to confirm the reported issue.
