### ISSUE TITLE
Errors raised in JSDoc does not stop building docs process

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor5-dev#550]
I've noticed that errors in documentation which appears in JSDoc don't stop building process and it is finished as complete without error. I noticed it when I saw errors on the master branch:
<img width="1139" alt="Screenshot 2019-08-13 at 12 59 00" src="https://user-images.githubusercontent.com/9017322/62937361-af16dd00-bdcc-11e9-9870-168890a60313.png">
What's more, there is a flag which seems to intentionally disable those errors with its default state: `If not passed, the errors will be printed to the console but the task will finish with '0'.`
https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-docs/lib/index.js

It seems like the wrong approach as allows to merge branches with errors in the documentation.

**Comment by msamsel** [comment]
cc @mlewand @Reinmar

**Comment by Reinmar** [comment]
I'm 99% sure it was causing the task to finish with an error code in the past. So this must be a regression.

But I wouldn't say that it necessarily has to stop the build. It could, if you think that this is the best option. But it can also continue and build the docs and just exit with the proper error code. That is useful when working on the docs because you can preview the docs without fixing that one last broken link that you have.

**Comment by Reinmar** [comment]
One thing to clarify here – we don't want the whole `yarn docs` to abort on the first step (which is gathering API info) when an error happened because that'd be frustrating (single typo would force you to re-run it).

We only want the `yarn docs` and `yarn docs:api` commands to exit with the proper error codes though to break the CI and documentation deploy.
